<!DOCTYPE html>
<html lang="en">
<head>
    <title>Jessica López - Contac</title>
    <meta charset="utf-8">
    <link rel="stylesheet" type="text/css" href="static/css/base.css">
    <link rel="stylesheet" type="text/css" href="static/css/contact.css">
</head>
<body>
    <div id="page-wrapper">
        <? include "common/header.phtml" ?>

        <section id="main-content">
        <h1>Contact me</h1>
            <img id="img-contact" src="static/images/contact-img">
            <img id="heart" src="static/images/heart.png">
            <div id="about-contact">
                Thank you so much for stopping by my website! <br>
                If you want to contact me please, drop me a message. <br>
                I would love to hear from you!
            </div>

            <form>
                <p>
                    <label>Name:
                        <input type="text" name="name" maxlength="30" required autofocus>
                    </label>
                </p>
                <p>
                    <label>Email:
                        <input type="email" name="email" maxlength="50" required>
                    </label>
                </p>
                <p>
                    <label> Message: <br>
                        <textarea name="message" rows="10" cols="50" required></textarea>
                    </label>
                </p>
                <p>
                    <input type="submit" value="Send">
                </p>
            </form>
        </section>

        <? include "common/footer.phtml" ?>
    </div>
</body>
</html>
