<!DOCTYPE html>
<html lang="en">
<head>
    <title>Jessica López - Graphic and Web Designer</title>
    <meta charset="utf-8">
    <meta name="descrption" content="Oslo-based web and graphic designer">
    <meta name="keywords" content="design, web, graphic, portfolio, works, project, logotype, logo, brand, website, brochure, diptych, oslo, norway">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="p:domain_verify" content="f89748d32dea02831e3131c56c958575"/>
    <? include "common/favicon.phtml" ?>
    <link rel="stylesheet" type="text/css" href="static/css/base.css">
    <link rel="stylesheet" type="text/css" href="static/css/index.css">
    <link rel="stylesheet" type="text/css" href="static/owl-carousel/owl.carousel.css">
    <link rel="stylesheet" type="text/css" href="static/owl-carousel/owl.theme.css">
</head>
<body>
    <div id="page-wrapper">
        <? include "common/header.phtml" ?>

        <section id="main-content">
            <article id="slider" class="owl-carousel">
                <div><img src="static/images/slider1a.jpg"></div>
                <div><img src="static/images/slider1b.jpg"></div>
            </article>

            <img id="heart" src="static/images/heart.png">

            <div id="social">
                <ul>
                    <li>
                        <a href="portfolio">
                            <img class="portfolio-img" src="static/images/graphicdesign.png" alt="portfolio">
                            <img src="static/images/graphicdesign_hover.png" alt="portfolio to graphic design">
                        </a>
                    </li>
                    <li>
                        <a href="portfolio">
                            <img class="portfolio-img" src="static/images/webdesign.png" alt="portfolio to web design">
                            <img src="static/images/webdesign_hover.png" alt="portfolio to web design">
                        </a>
                    </li>
                    <li>
                        <a href="contact">
                            <img class="hello-img" src="static/images/hello.png" alt="image to contact page">
                            <img src="static/images/hello_hover.png" alt="image to contact page">
                        </a>
                    </li>

                </ul>
            </div>
        </section>

        <? include "common/footer.phtml" ?>
    </div>

    <script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
    <script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/owl-carousel/1.3.2/owl.carousel.min.js"></script>
    <script type="text/javascript">
        jQuery(document).ready(function () {
            jQuery("#slider").owlCarousel({
                autoPlay: 5000,
                singleItem: true,
                pagination: false
            });
        });
    </script>
</body>
</html>
