<!DOCTYPE html>
<html lang="en">
<head>
    <title>Jessica López</title>
    <meta charset="utf-8">
    <link rel="stylesheet" type="text/css" href="static/css/base.css">
</head>
<body>
    <div id="page-wrapper">
        <? include "common/header.phtml" ?>

        <section id="main-content">
            <article id="slider"></article>
            <img id="heart" src="static/images/heart.png">
            <div id="social">
                <ul>
                    <li>
                        <a href="portfolio.phtml">
                            <img src="static/images/portfolioo.png" alt="portfolio">
                        </a>
                    </li>
                    <li>
                        <a href="contact.phtml">
                            <img src="static/images/hello.jpg" alt="mail">
                        </a>
                    </li>
                    <li>
                        <a target="_blank" href="http://www.flickr.com/photos/jessicalopezmarin/">
                            <img src="static/images/flickrr.png" alt="flickr">
                        </a>
                    </li>

                </ul>

            </div>
        </section>

        <? include "common/footer.phtml" ?>
    </div>
</body>
</html>
