<? $baseDir = '../'; ?>
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Jessica López</title>
    <meta charset="utf-8">
    <? include "../common/favicon.phtml" ?>
    <link rel="stylesheet" type="text/css" href="../static/css/base.css">
    <link rel="stylesheet" type="text/css" href="../static/css/about.css">
</head>
<body>
    <div id="page-wrapper">
        <? include "../common/header.phtml" ?>

        <section id="main-content">
            <h1 id="greeting">Hi!</h1>
            <img id="profile-picture" src="../static/images/photo.jpg" alt="About me">
            <p>
                My name is Jessica López.
            </p>
            <p>
                I am a graphic designer who recently got fascinated by web design. I design and develop visual communication concepts, from a logo to a web page.
            </p>

            <p>
                My tools of choice are Photoshop, Illustrator and InDesign from the Adobe Suite. And Sublime + Git when developing websites with HTML5 and CSS3, fields I’m still improving on.
            </p>
            <p>
                I am from Spain but I currently live in Norway, where I finished my Bachelor Degree in Advertising and Public Relations.
            </p>
            <p>
                When I am not moving pixels around, I like to walk and discover new places, taking pictures and learning Norwegian.
            </p>
            <p>
                If you want to know more about me please check out my <a target="blank" href="../download/CV_Jessica_Lopez.pdf"> online CV.</a>

            </p>
            <p>
                And don't hesitate to get in contact even if you just want to say "hello"!
            </p>
            <section class="about-norwegian">
                <p class="first-paragraph">
                    Jeg heter Jessica López.
                </p>
                <p>
                    Jeg er grafisk designer som nylig ble fasinert av web design. Jeg utformer og utvikler visuelle kommunikasjonskonsepter, alt fra logotyper til nettsider.
                </p>
                <p>
                    Verktøy som jeg behersker er Photoshop, Illustrator og InDesign fra Adobe Suite. Jeg bruker også Sublime + Git når jeg utvilker nettsider med HTML5 og CSS3, og jeg jobber hele tiden med å utvikle mine ferdigheter på disse områdene.
                </p>
                <p>
                    Jeg er fra Spania men bor i Norge, hvor jeg fullførte min Bachelor i Reklame og PPRR.
                </p>
                <p>
                    Når jeg ikke flytter piksler rundt, liker jeg å utforske nye steder, ta bilder og lære norsk.
                </p>
                <p>
                    Hvis du vil vite mer om meg, sjekk min <a target="blank" href="../download/CV_Jessica_Lopez.pdf"> CV her.</a>
                </p>
                <p>
                    Og nøl ikke med å ta kontakt med meg selv om du bare ønsker å si “hei”!
                </p>
            </section>
        </section>

        <? include "../common/footer.phtml" ?>
    </div>
</body>
</html>
