<? $baseDir = '../'; ?>
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Jessica López</title>
    <meta charset="utf-8">
    <link rel="stylesheet" type="text/css" href="../static/css/base.css">
    <link rel="stylesheet" type="text/css" href="../static/css/about.css">
</head>
<body>
    <div id="page-wrapper">
        <? include "../common/header.phtml" ?>

        <section id="main-content">
            <h1 id="greeting">Hi!</h1>
            <img id="profile-picture" src="../static/images/photo.jpg" alt="About me">
            <p>
                My name is Jessica López. I am a graphic and web designer living in Oslo. I was born in Spain in 1987 and moved to Norway in 2011 to study a Erasmus Program which I finished one year later. After that, I decided to stay here because I started loving some of the things I didn't have back in sunny Alicante: the snow, the green environment and the tranquillity.
            </p>
            <p>
                I have a Bachelor Degree in Advertising and Public Relations and studied a Master course in Graphic Design.
            </p>
            <p>
                Don't hesitate to get in contact even if you just want to say hello!
            </p>
            <p class="about-spanish first-paragraph">
                Soy Jessica López, una diseñadora gráfica y web que vive en Oslo. Nací en España en 1987 y me mudé a Noruega en 2011 para realizar una beca Erasmus la cual terminé un año más tarde. Después de ello, decidí quedarme aquí porque empecé a disfrutar de cosas que no había en Alicante, como la nieve, el paisaje verde y la tranquilidad.
            </p>
            <p class="about-spanish">
                Tengo una Licenciatura en Publicidad y Relaciones Públicas y estudié un curso de Diseño Gráfico y Gráfica Publicitaria.
            </p>
            <p class="about-spanish">
                No dudes en ponerte en contacto conmigo incluso si sólo quieres decirme ¡hola!
            </p>
        </section>

        <? include "../common/footer.phtml" ?>
    </div>
</body>
</html>
