<?
    $baseDir = '../';

    // List of projects to display (name => [description, orientation])
    $projects = array(
        'optica-videre' => array(
            'description' => 'Stationary for an optical shop' ,
            'orientation' => 'landscape',
        ),
        'cat-empire' => array(
            'description' => 'Poster for a music concert',
            'orientation' => 'portrait',
        ),
        'magazine-nomadas' => array(
            'description' => 'Travel magazine',
            'orientation' => 'landscape',
        ),
        'nordic-festival' => array(
            'description' => 'Poster for a festival in Oslo',
            'orientation' => 'portrait',
        ),

        'muffinitos' => array(
            'description' => 'Stationary for a bakery',
            'orientation' => 'landscape',
        ),
        'dgt' => array(
            'description' => 'Street Marketing',
            'orientation' => 'portrait',
        ),
    );
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Portfolio - Jessica López - Graphic and Web Designer</title>
    <meta charset="utf-8">
    <meta name="descrption" content="Know some of my recent works">
    <meta name="keywords" content="showcase, oslo, norway, design, web, graphic, portfolio, works, project, logotype, logo, brand, website, brochure, diptych">
    <? include "../common/favicon.phtml" ?>
    <link rel="stylesheet" type="text/css" href="../static/css/base.css">
    <link rel="stylesheet" type="text/css" href="../static/css/portfolio.css">
</head>
<body>
    <div id="page-wrapper">
        <? include "../common/header.phtml" ?>

        <h1>Some Projects</h1>

        <section id="main-content">
            <ul id="projects">
            <? foreach ($projects as $name => $project): ?>
                <li>
                    <figure class="project">
                        <a href="show.php?project=<?= $name ?>">
                            <img src="projects/<?= $name ?>/_thumbnail.jpg"
                                class="<?= $project['orientation'] ?>"
                                alt="<?= $project['description'] ?>">
                        </a>
                        <figcaption><?= $project['description'] ?></figcaption>
                    </figure>
                </li>
            <? endforeach; ?>
            </ul>
        </section>

        <? include "../common/footer.phtml" ?>
    </div>
</body>
</html>
