<?
    $baseDir = '../';

    // List of projects to display (name => [description, orientation])
    $projects = array(
        'muffinitos' => array(
            'description' => '',
            'orientation' => 'landscape',
        ),
        'optica-videre' => array(
            'description' => '',
            'orientation' => 'landscape',
        ),
        'cat-empire' => array(
            'description' => '',
            'orientation' => 'portrait',
        ),
        'nordic-festival' => array(
            'description' => '',
            'orientation' => 'portrait',
        ),
    );
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Jessica López</title>
    <meta charset="utf-8">
    <? include "../common/favicon.phtml" ?>
    <link rel="stylesheet" type="text/css" href="../static/css/base.css">
    <link rel="stylesheet" type="text/css" href="../static/css/portfolio.css">
</head>
<body>
    <div id="page-wrapper">
        <? include "../common/header.phtml" ?>

        <h1>Some Projects</h1>

        <section id="main-content">
            <ul id="projects">
            <? foreach ($projects as $name => $project): ?>
                <li>
                    <a href="show.php?project=<?= $name ?>">
                        <img src="projects/<?= $name ?>/_thumbnail.jpg"
                            class="<?= $project['orientation'] ?>"
                            alt="<?= $project['description'] ?>">
                    </a>
                </li>
            <? endforeach; ?>
            </ul>
        </section>

        <? include "../common/footer.phtml" ?>
    </div>
</body>
</html>
