<link rel="apple-touch-icon-precomposed" sizes="57x57"   href="<?= $baseDir ?>static/images/favicon/favicon-apple-touch-114.png">
<link rel="apple-touch-icon-precomposed" sizes="114x114" href="<?= $baseDir ?>static/images/favicon/favicon-apple-touch-114.png">
<link rel="apple-touch-icon-precomposed" sizes="72x72"   href="<?= $baseDir ?>static/images/favicon/favicon-apple-touch-144.png">
<link rel="apple-touch-icon-precomposed" sizes="144x144" href="<?= $baseDir ?>static/images/favicon/favicon-apple-touch-144.png">
<link rel="icon" sizes="32x32 48x48" href="<?= $baseDir ?>static/images/favicon/favicon.ico" type="image/vnd.microsoft.icon">
<link rel="icon" sizes="128x128" href="<?= $baseDir ?>static/images/favicon/favicon.icns">
<link rel="icon" href="<?= $baseDir ?>static/images/favicon/favicon.png" type="image/x-icon">
