<footer>
    <img id="footer-ribbon" src="<?= $baseDir ?>static/images/footer.png">
    <menu class="social-network-links">
        <li>
            <a target="_blank" href="http://www.linkedin.com/in/jessicalopezmarin/en">
                <img src="<?= $baseDir ?>static/images/ic-linked.png">
            </a>
        </li>
        <li>
            <a target="_blank" href="http://www.flickr.com/photos/jessicalopezmarin/">
                <img src="<?= $baseDir ?>static/images/ic-flic.png">
            </a>
        </li>
        <li>
            <a target="_blank" href="http://instagram.com/gexica">
                <img src="<?= $baseDir ?>static/images/ic-inst.png">
            </a>
        </li>
        <li>
            <a target="_blank" href="http://www.pinterest.com/jexica">
                <img src="<?= $baseDir ?>static/images/ic-pinter.png">
            </a>
        </li>
    </menu>
    <p>All works &copy; Jessica López 2014</p>
</footer>

<? @include "google-analytics.phtml" ?>
