<header>
    <menu id="social-networks">
        <li>
            <a target="_blank" href="http://www.linkedin.com/in/jessicalopezmarin/en">
                <img src="<?= $baseDir ?>static/images/icon-l.png">
            </a>
        </li>
        <li>
            <a target="_blank" href="http://www.flickr.com/photos/jessicalopezmarin/">
                <img src="<?= $baseDir ?>static/images/icon-f.png">
            </a>
        </li>
        <li>
            <a target="_blank" href="http://instagram.com/gexica">
                <img src="<?= $baseDir ?>static/images/icon-i.png">
            </a>
        </li>
        <li>
            <a target="_blank" href="http://www.pinterest.com/jexica">
                <img src="<?= $baseDir ?>static/images/icon-p.png">
            </a>
        </li>
    </menu>

    <nav id="header-navigation">
        <ul>
            <li>
                <a class="nav-link" href="<?= $baseDir ?>index.phtml" title="Sweet Home">Home</a>
            </li>
            <li>
                <a class="nav-link" href="<?= $baseDir ?>portfolio.phtml">Portfolio</a>
            </li>
            <li>
                <a class="nav-link" href="<?= $baseDir ?>about">About Me</a>
            </li>
            <li>
                <a class="nav-link" href="<?= $baseDir ?>contact.phtml">Contact</a>
            </li>
        </ul>
    </nav>
    <img id="logo" src="<?= $baseDir ?>static/images/logoo.png">
</header>
