<header>
    <menu id="social-networks">
        <li><a href="#"><img src="static/images/icon-l.png"></a></li>
        <li><a href="#"><img src="static/images/icon-f.png"></a></li>
        <li><a href="#"><img src="static/images/icon-i.png"></a></li>
        <li><a href="#"><img src="static/images/icon-p.png"></a></li>
    </menu>
    
    <nav id="header-navigation">
        <ul>
            <li>
                <a class="nav-link" href="index.phtml" title="Sweet Home">Home</a>
            </li>
            <li>
                <a class="nav-link" href="portfolio.phtml">Portfolio</a>
            </li>
            <li id="nav-logo"></li>
            <li>
                <a class="nav-link" href="about.phtml">About Me</a>
            </li>
            <li>
                <a class="nav-link" href="contact.phtml">Contact</a>
            </li>
        </ul>
    </nav>
</header>
